GET http://localhost:3000/posts/ 
###
GET http://localhost:3000/posts?owner=lina
###
GET http://localhost:3000/posts/674758890a52419e01d53f40
###
GET http://localhost:3000/posts/674758890a52419e01d53f40/comments/675c8a1cf17688ace315ddeb
###

GET http://localhost:3000/posts/674758890a52419e01d53f40/comments
###
POST http://localhost:3000/posts
Content-Type: application/json

{
    "owner":"lina",
    "title": "The best post",
    "content": "blablabla"
}
###
PUT http://localhost:3000/posts/674758890a52419e01d53f40
Content-Type: application/json

{
    "owner":"linoyosh!!!",
    "title": "The best post",
    "content": "blablabla"
}
###
POST http://localhost:3000/posts/674758890a52419e01d53f40/comments
Content-Type: application/json

{
    "owner":"queennnnnn !!!",
    "title": "im the queennn",
    "content": "blablabla"
}
###
PUT http://localhost:3000/posts/674758890a52419e01d53f40/comments/675c8a1cf17688ace315ddeb
Content-Type: application/json

{
    "owner":"linoyoshsss",
    "title": "The best post",
    "content": "blablabla"
}
###
DELETE http://localhost:3000/posts/674758940a52419e01d53f44

###
DELETE http://localhost:3000/posts/674758890a52419e01d53f40/comments/675c8a1bf17688ace315dde8
